yet another update to workflow [run-tests]

diff --git a/.github/workflows/run-tests.yml b/.github/workflows/run-tests.yml
--- a/.github/workflows/run-tests.yml
+++ b/.github/workflows/run-tests.yml
@@ -53,14 +53,18 @@ jobs:
           fi
 
           cd "$workdir/tests"
-            for dir in ./*/; do
+          echo "Current working directory: $(pwd)"
+            for dir in $workdir/tests/*/; do
             if [ -f "$dir/run_full_test.sh" ]; then
               echo "Running tests in $dir"
-              bash "cd $workdir/test; cd ./$dir; ./run_full_test.sh; cd $workdir/tests"
+              cd $workdir/test/$dir
+              bash "./run_full_test.sh"
               if [ "$MODE" = "exit" ] && [ $? -ne 0 ]; then
-              echo "Test failed in $dir, exiting."
-              exit 1
+                echo "Test failed in $dir, exiting."
+                exit 1
               fi
+              echo "Test completed in $dir"
+              cd $workdir/tests
             else
               echo "No run_full_test.sh in $dir, skipping."
             fi
